apiVersion: v1
kind: Service
metadata:
  name: bancario
spec:
  selector:
    app: bancario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # escolha uma porta entre 30000 e 32767
  type: NodePort
